### ISSUE TITLE
Session creation takes no notice of many settings.

### ISSUE THREAD

**Issue by jkp** [noahwilliamsson/openspotify#10]
Looking at the code it looks as if a number of things are ignored:
- appkey (beyond an internal check to see if it looks valid)
- user agent
- cache location
- temp file location

Am I reading things correctly? I was trying to see if my config structure needed to be valid for more than the duration of the call to sp_session_init() and it seems to me that only a few fields are referenced and the structure is not retained (a pointer to it) or copied.

If they aren't implemented, no worries, just trying to clarify how it is supposed to work.

**Comment by noahwilliamsson** [comment]
The answer is that neither the config structure nor any of its data needs to be retained after the call to sp_session_init(). They're all copied to internal locations.

The first two are simply ignored because despotify/libopenspotify uses a different handshake than libspotify and the official client. libspotify however, will make use of these two variables.

The other two settings are currently ignored because libopenspotify does not support caching of data pulled from the server.

**Comment by jkp** [comment]
OK, great: I was wondering if I could work with fairly temporary strings as the buffers for things like user_agent etc.  Seems I can.

Thanks for the quick response.
