### ISSUE TITLE
Race condition?

### ISSUE THREAD

**Issue by anonincog** [noahwilliamsson/openspotify#11]
If sp_session_player_load is issued several times in rapid succession (with the same or different tracks), openspotify crashes with a SIGSEGV. It may take a different number of calls each time, and GDB may reveal a different crash point each time, suggesting a race. The most "popular" point is the malloc on line 126 of player.c. 

The problem does NOT occur with the official libraries. I'm using git version 6f6e243 on Linux/GCC.

**Comment by noahwilliamsson** [comment]
This is a known issue and it's a race condition due to improper synchronization.

Among other things the encryption key for a previously requested track might end up being used in an attempt to decrypt a more recently loaded track.

The issue is in both sp_session.c:sp_session_player_load() and player.c:player_schedule() and player_ov_read() among other things.

I haven't decided howto solve this problem yet. The issue will probably sit around for a few more weeks until I've had time to think this through.

For now the workaround is to NOT do sp_session_player_load() "too fast" (i.e, before playback of the song has started and audio is being delivered)

**Comment by anonincog** [comment]
Oh, sorry about that. I tried searching the commit log for a mention of the problem, but since I found nothing I reported it. Thanks for the quick reply and workaround.

**Comment by noahwilliamsson** [comment]
It was listed in libopenspotify/TODO.txt.
I've now moved the known issues listed there into KNOWN_ISSUES.txt instead.
Thanks for the report!
